lab_4/urls.py
from django.urls import path
from .views import index, jastip, jastipabout, jastiphto, jastippict, formmember

urlpatterns = [
    path('', index, name='index'),
    path('jastip/', jastip, name='jastip'),
    path('jastip/about/', jastipabout, name='about'),
    path('jastip/hto/',jastiphto, name='hto'),
    path('jastip/pict/',jastippict, name='pict'),
    path('formmember/',formmember, name=''),

]

lab_5/urls.py
from django.urls import path
from .views import schedule_new, schedule_list, schedule_delete

urlpatterns = [
    path('newsf/', schedule_new),
    path('schedule_list/', schedule_list, name='schedule_list'),
    path('deleteAllSchedule', schedule_delete, name='schedule_delete'),
]

praktikum/urls.py
from django.conf.urls import include, url
from django.urls import re_path
from django.contrib import admin
import lab_4.urls as lab_4
import lab_5.urls as lab_5
from story8.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-4/', include(('lab_4.urls', 'lab_4'), namespace = 'lab_4')),
    url(r'^lab_5/', include(('lab_5.urls', 'lab_5'), namespace = 'lab_5')),
    url(r'^story8/', my_profile),
	url(r'^story8/formmember', formmember),
    
]

story8/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('formmember/',formmember),

]

lab_4/models.py
from django.db import models
from django.core.exceptions import ValidationError


class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=32)
    
    @classmethod
    def is_email_registered(cls, value):
        if not cls.objects.filter(email=value).exists():
            raise ValidationError("This e-mail is not registered", params={"value": value})

lab_5/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Schedule(models.Model):
    date = models.DateTimeField()
    place = models.CharField(max_length=100)
    event = models.CharField(max_length=100)
    category = models.CharField(max_length=30)

latppw/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

class Subsme(models.Model):
    name = models.CharField(max_length = 50)
    password = models.CharField(max_length = 20)
    email = models.CharField(max_length = 50)

lab_4/forms.py
from django import forms

class SubscribeForm(forms.Form):
    email_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Example: hira@gmail.com',
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Full Name',
    }
    pass_attrs = {
        'type': 'password',
        'class': 'form-control',
        'placeholder':'Password',
    }
    name = forms.CharField(max_length = 50, error_messages={"required": "Please enter your name"}, widget = forms.TextInput(attrs=name_attrs))
    password = forms.CharField(max_length = 20, min_length=6, widget = forms.PasswordInput(attrs=pass_attrs), error_messages={"min_length": "password must be longer than 5 characters"})
    email = forms.EmailField(error_messages={"required": "Please enter a valid email"}, max_length=50, widget=forms.TextInput(attrs=email_attrs))

lab_5/forms.py
from django import forms

from .models import Schedule

# class Date(forms.DateTimeInput):
#     input_type = 'datetime-local'

class ScheduleForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ('date', 'place', 'event','category')

story8/forms.py
from django import forms




class SubsmeForm(forms.Form):
    email_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Example: hira@gmail.com',
    }
    usr_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Full usr',
    }
    pass_attrs = {
        'type': 'pwd',
        'class': 'form-control',
        'placeholder':'pwd',
    }
    usr = forms.CharField(max_length = 50, error_messages={"required": "Please enter your usr"}, widget = forms.TextInput(attrs=usr_attrs))
    pwd = forms.CharField(max_length = 20, min_length=6, widget = forms.pwdInput(attrs=pass_attrs), error_messages={"min_length": "pwd must be longer than 5 characters"})
    email = forms.EmailField(error_messages={"required": "Please enter a valid email"}, max_length=50, widget=forms.TextInput(attrs=email_attrs))

lab_4/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'lab_4/My Profile.html')

def jastip(request):
    return render(request, 'lab_4/jastip.html')

def jastiphto(request):
    return render(request, 'lab_4/jastiphto.html')

def jastippict(request):
    return render(request, 'lab_4/jastippict.html')

def jastipabout(request):
    return render(request, 'lab_4/jastipabout.html')

def formmember(request):
    return render(request, 'lab_4/formmember.html')
    

def subscribe(request):
    response = {}
    response["forms"] = SubscribeForm()
    return render(request, 'subscribe.html', response)


@csrf_exempt
def validate(request):
    email = request.POST.get("email")
    data = {'not_valid': Subscriber.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(data)

def success(request):
    submited_form = SubscribeForm(request.POST or None)
    if (submited_form.is_valid()):
        cd = submited_form.cleaned_data
        new_subscriber = Subscriber(name=cd['name'], password=cd['password'], email=cd['email'])
        new_subscriber.save()
        data = {'name': cd['name'], 'password': cd['password'], 'email': cd['email']}
    return JsonResponse(data)
    

lab_5/views.py
from django.shortcuts import render, redirect
from .forms import ScheduleForm
from .models import Schedule
# Create your views here.

def schedule_delete(request):
    schedule = Schedule.objects.all().delete()
    return render(request, 'ListSchedule.html', {'schedules': schedule})

def schedule_list(request):
    schedule = Schedule.objects.all().values()
    return render(request, 'ListSchedule.html', {'schedules': schedule})

def schedule_new(request):
    if request.method == "POST":
        form = ScheduleForm(request.POST)
        if form.is_valid():
            new_sch = form.save()
            new_sch.save()
            return redirect('/lab_5/schedule_list/')
    else:
        form = ScheduleForm()
    return render(request,'Scheduleforms.html', {'form': form})

latppw/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse



import requests
import json
Create your views here.
def mydiatry(request):


    tgl = request.GET['tgl']
    catatan = request.GET['catatan']
    json = JsonResponse( {“tgl”:tgl,“catatan”:catatan}, safe=False )
    return json

    

story8/views.py
from django.shortcuts import render

def my_profile(request):
	return render(request,"mybio.html",{})

def formmember(request):
    return render(request, 'story8/formmember.html')


def subsme(request):
    response = {}
    response["forms"] = subsmeForm()
    return render(request, 'subsme.html', response)


@csrf_exempt
def validate(request):
    email = request.POST.get("email")
    data = {'not_valid': subsmer.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(data)

def yes(request):
    submited_form = subsmeForm(request.POST or None)
    if (submited_form.is_valid()):
        cd = submited_form.cleaned_data
        new_subsmer = subsmer(name=cd['name'], password=cd['password'], email=cd['email'])
        new_subsmer.save()
        data = {'name': cd['name'], 'password': cd['password'], 'email': cd['email']}
    return JsonResponse(data)
    



# Create your views here.

lab_4/templates/lab_4/My Profile.html
{% load static %}

<html>
<head>
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/lato" type="text/css"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="{% static '/lab_4/myprofbg.css' %}" type="text/css" rel = "stylesheet">
<title>Faza's Profile</title>

</head>
<body>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-4">
      <img id="fotoku" src="https://ibb.co/fnBZVL" class="img-rounded" alt="Cinque Terre" width="100%">
      <img id="quote" src="https://ibb.co/dT6jVL" class="img-rounded" alt="Cinque Terre" width="100%">
      <img id="motivation" src="https://ibb.co/gFuXH0" class="img-rounded" alt="Cinque Terre" width="100%">
    </div>
    <div class="col-md-7">
      <h1 id="myname"> Faza Siti Sabira Prakoso</h1>
      <h2 id="ui">Student at University of Indonesia</h2>
      <h3 id="dream">Business woman <a href="/lab-4/jastip/" target="_blank"><button type="button" class="btn btn-primary">JASTIP</button alt="Download" class="img download"></a>     
      </h3>
      
      <img id="experiences"src="https://ibb.co/b6oEVL" class="img-rounded" alt="Cinque Terre" width="80%">
      <img id="education"src="https://ibb.co/efynjf" class="img-rounded" alt="Cinque Terre" width="70%">
      <img id="contact"src="https://ibb.co/eTPGc0" class="img-rounded" alt="Cinque Terre" width="60%">

      <a href="/lab-4/formmember" target="_blank"><button type="button" class="btn btn-default">JOIN ME</button alt="Download" class="img download"></a>     
      

      
      </div>
    </div>
  </div>
</body>
</html>

lab_4/templates/lab_4/formmember.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static 'lab_4/myprofbg.css' %}" type="text/css" rel = "stylesheet">
    <title>Member Form</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  
  <div class="container">
    
    <h2>Register Account</h2>
    <form action="/action_page.php">
    
        <div class="form-group">
            <label for="usr">Name:</label>
            <input type="text" class="form-control" id="usr">
        </div>
      
     
      
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
      </div>


      
      <div class="form-group">
        <label for="pwd">Password:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
      </div>
      
     
      
      <button type="button" class="btn btn-success">Submit</button>
      
      
  
  </body>

</head>

</html>

lab_4/templates/lab_4/jastip.html
{% load static %}

<html>
<head>
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/lato" type="text/css"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="{% static 'lab_4/myprofbg.css' %}" type="text/css" rel = "stylesheet">
</head>
</head>
<body>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <img id="fototas" src="https://lh3.googleusercontent.com/B2os4OTjaYXMymV2boXpr6AvgPqAcSa9dB1NThwAwji-aDBPBdOV7VNSaLYXFs7AoZHD2YKs1atm65L7Wy0dDFz4qKggI_dJ6jOCYHzSaYnrtsGNDuLqoM5k8E7p2WZechclmOM9l5VFHPPuuLnEBAJYUNVrFBL-WZKOOb5IvFUaGZGFhuewSXTE4-ko6_sJxNKrAvIIChmj6Ec9C-jN7spfoAkkbcgqQPAHHEu4K43iPL7blOZnquhIiHY4IPKzjJqDgcUAyAa0wf6sbZ88oeACk7Y1NSxXqsgTTESHwxeiKMwqlwmn6hMQSh8bQHpflykvZU7_tZbJ5boeG5ouK3rnIHZjA-Jr1BMwki4xIaM2aZwYq5vND6BgEk3RzgL_0I0s3MrVDYysAEKzwxyxu52xgH_67HVwqsgX79bIOjuxk8RqWnGpAviJLclYMEEMH-SK_dhbabwH66FOC3LXRJ21WWk4jMPKMBzkkxr4xhi8SH8EYkzWt5cPjp9xHFZ6kY57VBktcqLZZy9rDq2x6kyRZGyQlRJz1uVzIgsC5koZ_yc81oyUI5CEflvsvQLb5UADSMAf6mi87TFnd1K-E0wcjZpeFKq7oYJi17JOq7-7rCFgEFx4oSCXaW2Q1rs=w640-h438-no" class="img-rounded" alt="Cinque Terre" width="100%">  
        </div>
        <div class="col-md-6">
            <h1 id="jastip">Jastip Tas Ori</h1>
            <h2 id="jastip">Jasa titip tas original terpercaya</h2>
            <h3 id="jastip">Open order by request</h3>
            <h3 id="jastip">PO Singapore 30 Sept - 3 Okt 2018</h3>
            <h3 id="jastip">Shipment 7 Okt 2018</h3>
            <h3 id="jastip">Oder via LINE only: fazazabira</h3>           
        </div>
    </div>

    <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-6">
                <a href="/lab-4/jastip/" target="_blank"><button type="button" class="btn btn-danger">HOME</button alt="Download" class="img download"></a>       
                <a href="/lab-4/jastip/about" target="_blank"><button type="button" class="btn btn-warning">ABOUT</button alt="Download" class="img download"></a>       
                <a href="/lab-4/jastip/hto" target="_blank"><button type="button" class="btn btn-success">HOW TO ORDER</button alt="Download" class="img download"></a>       
                <a href="/lab-4/jastip/pict" target="_blank"><button type="button" class="btn btn-info">PICTURE</button alt="Download" class="img download"></a>       
                    
            </div>
            <div class="col-md-5">
                
            </div>
    </div>

    <div class="row">
            <div class="col-md-1"></div>
            <div class="background col-md-6">
                
                <h3>Welcome to jasa titip tas original!</h3>
                <h3>Kami menyediakan jasa titip tas original.</h3>    
                <h3>Harga yang tertera sudah termasuk jasa titipnya.</h3>    
                <h3>Happy shopping!</h3>
                
            </div>
            <div class="col-md-5">
                
            </div>
    </div>

</body>

</html>

lab_4/templates/lab_4/jastipabout.html
{% load static %}

<html>
<head>
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/lato" type="text/css"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="{% static 'lab_4/myprofbg.css' %}" type="text/css" rel = "stylesheet">
</head>
</head>
<body>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <img id="fototas" src="https://lh3.googleusercontent.com/B2os4OTjaYXMymV2boXpr6AvgPqAcSa9dB1NThwAwji-aDBPBdOV7VNSaLYXFs7AoZHD2YKs1atm65L7Wy0dDFz4qKggI_dJ6jOCYHzSaYnrtsGNDuLqoM5k8E7p2WZechclmOM9l5VFHPPuuLnEBAJYUNVrFBL-WZKOOb5IvFUaGZGFhuewSXTE4-ko6_sJxNKrAvIIChmj6Ec9C-jN7spfoAkkbcgqQPAHHEu4K43iPL7blOZnquhIiHY4IPKzjJqDgcUAyAa0wf6sbZ88oeACk7Y1NSxXqsgTTESHwxeiKMwqlwmn6hMQSh8bQHpflykvZU7_tZbJ5boeG5ouK3rnIHZjA-Jr1BMwki4xIaM2aZwYq5vND6BgEk3RzgL_0I0s3MrVDYysAEKzwxyxu52xgH_67HVwqsgX79bIOjuxk8RqWnGpAviJLclYMEEMH-SK_dhbabwH66FOC3LXRJ21WWk4jMPKMBzkkxr4xhi8SH8EYkzWt5cPjp9xHFZ6kY57VBktcqLZZy9rDq2x6kyRZGyQlRJz1uVzIgsC5koZ_yc81oyUI5CEflvsvQLb5UADSMAf6mi87TFnd1K-E0wcjZpeFKq7oYJi17JOq7-7rCFgEFx4oSCXaW2Q1rs=w640-h438-no" class="img-rounded" alt="Cinque Terre" width="100%">  
        </div>
        <div class="col-md-6">
            <h1>Jastip Tas Ori</h1>
            <h2>Jasa titip tas original terpercaya</h2>
            <h3>Open order by request</h3>
            <h3>PO Singapore 30 Sept - 3 Okt 2018</h3>
            <h3>Shipment 7 Okt 2018</h3>
            <h3>Oder via LINE only: fazazabira</h3>           
        </div>
    </div>

    <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-6">
                <a href="/lab-4/jastip/" target="_blank"><button type="button" class="btn btn-danger">HOME</button alt="Download" class="img download"></a>       
                <a href="/lab-4/jastip/about" target="_blank"><button type="button" class="btn btn-warning">ABOUT</button alt="Download" class="img download"></a>       
                <a href="/lab-4/jastip/hto" target="_blank"><button type="button" class="btn btn-success">HOW TO ORDER</button alt="Download" class="img download"></a>       
                <a href="/lab-4/jastip/pict" target="_blank"><button type="button" class="btn btn-info">PICTURE</button alt="Download" class="img download"></a>       
                    
            
            </div>
            <div class="col-md-5">
                
            </div>
    </div>

    <div class="row">
            <div class="col-md-1"></div>
            <div class="background col-md-8">
                
                <h3>Jastip dikenal juga dengan istilah Personal Shopper adalah </h3>
                <h3>sebuah pekerjaan keluar masuk toko, mall atau marchant besar</h3>    
                <h3>dengan beberapa merek terkenal sesuai dengan keinginan para</h3>    
                <h3>pelanggan yang percaya pada jasa mereka. </h3>    
                <h3></h3>
                <h3>So, buat kamu para ladies yang lagi butuh sesuatu tapi nggak </h3>    
                <h3>sempet membeli barang tersebut, kamu bisa banget loh pakai </h3>    
                <h3>jasa kami!</h3>    
                        
                        
                
            </div>
            <div class="col-md-3">
                
            </div>
    </div>

</body>

</html>

lab_4/templates/lab_4/jastipnavbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href='https://fonts.googleapis.com/css?family=Pattaya' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600" rel="stylesheet">

    {% load static %}
    <link href="{% static 'myprofbg.css' %}" type="text/css" rel="stylesheet"/>

  </head>
  <body>
  	<div class="button-shape"> </div>
  	<div class="button">
        <a href="/lab_4/jastip/" target="_blank"><button type="button" class="btn btn-primary">JASTIP</button alt="Download" class="img download"></a>     
      
  	</div> 
  </body>
</html>

lab_5/templates/ListSchedule.html
{% load static %}

<!DOCTYPE html>
<html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="{% static '/lab_5/sched.css' %}" type="text/css" rel = "stylesheet">

<title>Faza's Daily Schedule</title>
<body>
    <div class="row">
        <div class = "col-md-4"></div>
    <h1 id="judul2">Faza's Daily Schedule</h1>
    </div>

    <div class="row">
        <div class="col-md-9"></div>
        
            <a href="{% url 'lab_5:schedule_delete' %}" type="button" class="btn btn-danger">Delete All Schedule</a>
        
    </div>

    {% for schedule in schedules %}

    <div class = "row">
        <div class="col-md-3"></div>
        <div>
            <p>Tanggal: {{ schedule.date }}</p>
            <p>Tempat: {{ schedule.place }}</p>
            <p>Event: {{ schedule.event }}</p>
            <p>Kategori: {{ schedule.category }}</p>
        </div>
    </div>
    <br>
    {% endfor %}
</body>
</html>

lab_5/templates/Scheduleforms.html
{% load static %}

<!DOCTYPE html>
<html>

<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>
<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/lato" type="text/css"/>        
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="{% static '/lab_5/sched.css' %}" type="text/css" rel = "stylesheet">

<title>Faza's Daily Schedule</title>
<body>
    <div class ="row">
        <div class = "col-md-2"></div>
        <div>
                <h1 id="judul"><a href="\lab-4\">Faza's Daily Schedule</a></h1>
            </div>
            
    </div>
    
    <div class = "row">
        <div class = "col-md-4"></div>
            {% for schedule in schedules %}
                <div>
                    <p>published: {{ post.published_date }}</p>
                    <h1><a href="">{{ post.title }}</a></h1>
                    <p>{{ post.text|linebreaksbr }}</p>
                </div>
            {% endfor %}
    
                
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Submit</button>
    </form>
    </div>

</body>
</html>